# Generated by Django 5.0.4 on 2024-06-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('phone_verification_code', models.CharField(blank=True, max_length=7)),
                ('password', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
