# Generated by Django 5.0.4 on 2024-06-03 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(8)]),
        ),
    ]
