# Generated by Django 5.0.4 on 2024-06-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_registration_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
