# Generated by Django 5.0.4 on 2024-06-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_rename_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
