# Generated by Django 5.0.4 on 2024-06-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
