# Generated by Django 5.0.4 on 2024-06-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupInHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
