# Generated by Django 5.0.4 on 2024-06-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_signupinhome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignupInHome',
            new_name='SimpleSignup',
        ),
        migrations.AlterModelOptions(
            name='simplesignup',
            options={'verbose_name': "simple registration's name", 'verbose_name_plural': "simple registrations' name"},
        ),
    ]
