# Generated by Django 5.0.4 on 2024-06-06 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_signupinhome_simplesignup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplesignup',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='simplesignup',
            name='phone',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(11)]),
        ),
    ]
