# Generated by Django 5.0.4 on 2024-06-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_simplesignup_date_alter_simplesignup_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplesignup',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
