# Generated by Django 5.0.4 on 2024-06-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_simplesignup_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleSignup',
        ),
    ]
