# Generated by Django 5.0.4 on 2024-06-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_simplesignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('is_checked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "simple registration's name",
                'verbose_name_plural': "simple registrations' name",
            },
        ),
    ]
