# Generated by Django 5.0.4 on 2024-06-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_simplesignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplesignup',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
