# Generated by Django 5.0.4 on 2024-06-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_simplesignup_is_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplesignup',
            name='is_submitted',
        ),
    ]
