# Generated by Django 5.0.4 on 2024-06-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_simplesignup_is_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplesignup',
            name='email',
        ),
    ]
