# Generated by Django 5.0.4 on 2024-05-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_book_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book Category')),
                ('url_title', models.CharField(max_length=100, verbose_name='URL Book Category')),
            ],
        ),
    ]
