# Generated by Django 5.0.4 on 2024-05-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_book_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ages',
            field=models.CharField(default='All', max_length=100),
        ),
    ]
