# Generated by Django 5.0.4 on 2024-05-24 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_type_delete_category_book_category_book_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book Age')),
                ('url_title', models.CharField(max_length=100, verbose_name='URL Book Age')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book Category')),
                ('url_title', models.CharField(max_length=100, verbose_name='URL Book Category')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book Level')),
                ('url_title', models.CharField(max_length=100, verbose_name='URL Book Level')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ages',
        ),
        migrations.AddField(
            model_name='book',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.age'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.level'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
