# Generated by Django 5.0.4 on 2024-05-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_age_category_level_remove_book_type_remove_book_ages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='book',
            name='title_fa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Title'),
        ),
    ]
