# Generated by Django 5.0.4 on 2024-05-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Book Image'),
        ),
    ]
