# Generated by Django 5.0.4 on 2024-05-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
