# Generated by Django 5.0.4 on 2024-05-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url_title',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
