# Generated by Django 5.0.4 on 2024-05-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_category_url_title_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='age',
            name='url_title',
        ),
        migrations.RemoveField(
            model_name='level',
            name='url_title',
        ),
        migrations.RemoveField(
            model_name='type',
            name='url_type',
        ),
        migrations.AddField(
            model_name='age',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='level',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug'),
        ),
    ]
